### ISSUE TITLE
APNS Message Sending in 1.6.0

### ISSUE THREAD

**Issue by kirtan73** [jazzband/django-push-notifications#469]
I have followed the steps as per given in documentation of version 1.4.0 and tried for 1.6.0 to send a notification but giving this error cannot understand what is it?

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/aubergine/Desktop/final_fcm/fcm_env/local/lib/python2.7/site-packages/push_notifications/models.py", line 167, in send_message
    **kwargs
  File "/home/aubergine/Desktop/final_fcm/fcm_env/local/lib/python2.7/site-packages/push_notifications/apns.py", line 113, in apns_send_message
    certfile=certfile, **kwargs
  File "/home/aubergine/Desktop/final_fcm/fcm_env/local/lib/python2.7/site-packages/push_notifications/apns.py", line 94, in _apns_send
    **notification_kwargs
  File "/home/aubergine/Desktop/final_fcm/fcm_env/local/lib/python2.7/site-packages/apns2/client.py", line 54, in send_notification
    stream_id = self.send_notification_async(token_hex, notification, topic, priority, expiration, collapse_id)
  File "/home/aubergine/Desktop/final_fcm/fcm_env/local/lib/python2.7/site-packages/apns2/client.py", line 66, in send_notification_async
    json_payload = json_str.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 57: ordinal not in range(128)

**Comment by kirtan73** [comment]
I was sending smilie in a message so it was showing encoding error.
