### ISSUE TITLE
APNSServerError: ConnectionFailed when testing from django shell

### ISSUE THREAD

**Issue by haleydr82** [jazzband/django-push-notifications#496]
Receiving a 'ConnectionFailed' error when trying to send a test message from the django shell:

>>> from push_notifications.models import APNSDevice
>>> device = APNSDevice.objects.get(id=2)
>>> device
<APNSDevice: dave>
>>> device.send_message("Test")
No handlers could be found for logger "apns2.client"
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/push_notifications/models.py", line 167, in send_message
    **kwargs
  File "/usr/lib/python2.7/site-packages/push_notifications/apns.py", line 120, in apns_send_message
    raise APNSServerError(status=reason_for_exception_class(apns2_exception.__class__))
APNSServerError: ConnectionFailed

Looking at the packet capture (screenshot attached)  I can see that the SSL handshake with the APNS server appears to be successful, but then the connection is reset.

![Screen Shot 2019-04-30 at 2 38 15 PM](https://user-images.githubusercontent.com/7938638/56985115-9ce29d00-6b55-11e9-9f75-8f7749c01cc7.png)

**Comment by elcolie** [comment]
I confirm. With the `master`. 
`-e git+git@github.com:jazzband/django-push-notifications.git@c4a0d710711fa27bfb6533c0bf3468cb67a62679#egg=django_push_notifications`
I don't have a problem.

**Comment by nadiacq** [comment]
Any solution?
