### ISSUE TITLE
_apns_prepare => TypeError: __init__() got multiple values for argument 'custom'

### ISSUE THREAD

**Issue by RaD** [jazzband/django-push-notifications#518]
Version: 1.6.0
```
Traceback (most recent call last):
  File "/opt/project/src/api/views.py", line 203, in send_push_notification
    push.send_message(msg)  # ToDo: i18n
  File "/usr/lib/python3.6/site-packages/push_notifications/models.py", line 167, in send_message
    **kwargs
  File "/usr/lib/python3.6/site-packages/push_notifications/apns.py", line 113, in apns_send_message
    certfile=certfile, **kwargs
  File "/usr/lib/python3.6/site-packages/push_notifications/apns.py", line 90, in _apns_send
    data = _apns_prepare(registration_id, alert, **kwargs)
  File "/usr/lib/python3.6/site-packages/push_notifications/apns.py", line 60, in _apns_prepare
    url_args, custom=extra, thread_id=thread_id)
TypeError: __init__() got multiple values for argument 'custom'
```

**Comment by RaD** [comment]
Just upgrade to 1.6.1
