### ISSUE TITLE
apns_send_message -> push_notifications.apns.APNSServerError: BadDeviceToken

### ISSUE THREAD

**Issue by RaD** [jazzband/django-push-notifications#519]
Version: 1.6.1
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/push_notifications/apns.py", line 113, in apns_send_message
    certfile=certfile, **kwargs
  File "/usr/lib/python3.6/site-packages/push_notifications/apns.py", line 94, in _apns_send
    **notification_kwargs
  File "/usr/lib/python3.6/site-packages/apns2/client.py", line 83, in send_notification
    raise exception_class_for_reason(result)
apns2.errors.BadDeviceToken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/project/src/api/views.py", line 203, in send_push_notification
    push.send_message(msg)  # ToDo: i18n
  File "/usr/lib/python3.6/site-packages/push_notifications/models.py", line 167, in send_message
    **kwargs
  File "/usr/lib/python3.6/site-packages/push_notifications/apns.py", line 120, in apns_send_message
    raise APNSServerError(status=reason_for_exception_class(apns2_exception.__class__))
push_notifications.apns.APNSServerError: BadDeviceToken
```

**Comment by RaD** [comment]
Drop all APNS tokens via admin interface.
